import Sidebar from "@/components/containers/Sidebar/sidebar";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import PlayerContextProvider from "@/contexts/PlayerContext";

const robotoSans = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["cyrillic", "greek", "latin"],
});

export const metadata: Metadata = {
  title: "Waves",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
    <html lang="en">
      <PlayerContextProvider>
        <body className={`${robotoSans.className} antialiased`}>
          <Sidebar>{children}</Sidebar>
          <audio src="" preload="auto" />
        </body>
      </PlayerContextProvider>
    </html>
    // </ClerkProvider>
  );
}
