import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import Sidebar from "@/components/containers/Sidebar/sidebar";

const robotoSans = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["cyrillic", "greek", "latin"],
});

export const metadata: Metadata = {
  title: "Waves",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.className} antialiased`}>
        <Sidebar>{children}</Sidebar>
      </body>
    </html>
  );
}
