import { PlayerProvider } from "@/components/context/PlayerContext/PlayerContext";
import Sidebar from "@/components/containers/Sidebar/sidebar";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/components/layouts/ConvexClientProvider";
import { ConvexQueryCacheProvider } from "convex-helpers/react/cache/provider";

const robotoSans = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["cyrillic", "greek", "latin"],
});

export const metadata: Metadata = {
  title: "Waves",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.className} antialiased`}>
        <ConvexClientProvider>
          <ConvexQueryCacheProvider>
            <PlayerProvider>
              <Sidebar>{children}</Sidebar>
            </PlayerProvider>
          </ConvexQueryCacheProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
